version: "3.3"
services:
  web:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../:/code
    environment:
      FLASK_ENV: development
  redis:
    image: redis
